//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PNGDBEntities : DbContext
    {
        public PNGDBEntities()
            : base("name=PNGDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_Account> A_Account { get; set; }
        public virtual DbSet<A_JournalEntry> A_JournalEntry { get; set; }
        public virtual DbSet<A_JournalEntryDetails> A_JournalEntryDetails { get; set; }
    }
}
